// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> DensityMap;
RWTexture2D<float4> Mask;
RWTexture2D<float4> PlantDensity;
float viability;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    PlantDensity[id.xy] = float4(1, 1, 1, 0.0);
}
